Amend startup timings to improve stability
rosco-m68k/rosco_m68k pull request #152
Opened 2020-11-27 11:16 UTC by mattuna15

- add small delay before kermit init
- increase delay during receive
- add some error messages

2020-11-28 20:42 UTC, roscopeco requested changes
Thanks for the PR! :) 

I left a couple of minor comments.

Also, would you mind retargeting this to  the `release/revision-1.2` branch please? I will add it into a new minor version and release it (and then merge it back to develop and pull the changes into the current development firmware).

2020-11-28 20:42 UTC, roscopeco commented on .gitignore
> +code/firmware/emucon/emucon2.tos
These gitignore changes don't feel generally applicable, can they be removed please?

2020-11-28 20:42 UTC, roscopeco commented on code/firmware/rosco_m68k_v1.2/stage2/kermit/kermit_support.c
> +            mcPrint("\x1b[1;31mSEVERE\x1b[0m: Run failed failed\r\n");
Is "failed failed" a typo?

2020-11-28 20:42 UTC, roscopeco commented on code/firmware/rosco_m68k_v1.2/stage2/main2.c
> +    mcBusywait(500000);
Would 400000 do the trick here? That would match the delay that has been added to the current development firmware.

2020-11-29 07:04 UTC, mattuna15 commented
Moved to new branch release 1.2

2020-11-29 07:04 UTC, closed without merging