Add SST flash lib and demo
rosco-m68k/rosco_m68k pull request #233
Opened 2021-07-06 11:59 UTC by roscopeco

Adds a library to support direct interface (including erase and write) to SST39SF0x0 flash devices, and a small demo for use with HUGEROM / Pro systems.

The included demo is also intended to serve as a useful POC for a writeable configuration area in ROM as suggested by @XarkLabs . 

Proof of life; Notice "old data" (read from flash) and "new data" (written to flash) is swapped with each run (note: powered down for 1m between the two runs):

<img width="711" alt="Screenshot 2021-07-06 at 12 14 48" src="https://user-images.githubusercontent.com/2096421/124596108-ca27e580-de59-11eb-92a0-f56c3e7ab33a.png">

2021-07-06 17:17 UTC, 0xTJ reviewed
Aside from those couple little things, the code looks good to me!

2021-07-06 17:17 UTC, 0xTJ commented on code/software/libs/src/sst_flash/sst.c
> +static void unlock(uint32_t rom_base) {
From the datasheet, it seems to me that the DQ6 toggling only happens for the Program and Erase operations, not after individual writes of the commands. I'd think that we only want to call `wait` in `sst_sector_erase`, `sst_sector_erase`, and `sst_write_byte`, but not in `unlock` or in `sst_command`.

2021-07-06 17:17 UTC, 0xTJ commented on code/software/libs/src/sst_flash/sst.c
> +    uint8_t *p = (uint8_t*)addr;
It's a minor thing, and I'm not sure it's needed, but I'd consider making all the `uint8_t *p` be `volatile`, just to make sure that the compiler doesn't have the chance to inline and optimize-out any writes at some point in the future.

2021-07-06 17:52 UTC, roscopeco reviewed
Thanks for looking @0xTJ , I've pushed some changes and added some comments for context :)

2021-07-06 17:52 UTC, roscopeco commented on code/software/libs/src/sst_flash/sst.c
> +static void unlock(uint32_t rom_base) {
Interestingly, this was my read of the data sheet too, however in testing I found that, without the waits, it didn't work. I just tried it again and reliably get this:

```
Kernel received okay; Starting...


rosco_m68k Flash EEPROM identifier / write POC
**********************************************

EVEN ROM is  <Unknown>  [Manufacturer ???]
ODD  ROM is  <Unknown>  [Manufacturer ???]

Config area is 1 sector per ROM (2 total)
  Sector num : 0x7f
  Sector size: 4096 bytes
  Total size : 8192 bytes
  Base addr  : 0x00efe000

Old data: 0xaa55aa55 0xaa55aa55 0xaa55aa55...
New data: 0xaa55aa55 0xaa55aa55 0xaa55aa55...
```

_However_ , I now suspect that the call to write was just preventing an optimisation (which you mention in your other comment). Making the write value in `write` be volatile allows these `wait`s to be removed, while keeping everything working, so looks like this is a doubly-good shout, thanks! :)

2021-07-06 17:52 UTC, roscopeco commented on code/software/libs/src/sst_flash/sst.c
> +    uint8_t *p = (uint8_t*)addr;
See reply to your other comment, but long story short this is totally necessary, good spot!

With this being `volatile` and the `wait`s removed, I'm now getting this:

```
Kernel received okay; Starting...


rosco_m68k Flash EEPROM identifier / write POC
**********************************************

EVEN ROM is SST39SF040  [Manufacturer SST]
ODD  ROM is SST39SF040  [Manufacturer SST]

Config area is 1 sector per ROM (2 total)
  Sector num : 0x7f
  Sector size: 4096 bytes
  Total size : 8192 bytes
  Base addr  : 0x00efe000

Old data: 0x55aa55aa 0x55aa55aa 0x55aa55aa...
New data: 0xaa55aa55 0xaa55aa55 0xaa55aa55...
```

2021-07-06 23:16 UTC, roscopeco commented
I just pushed the first cut of a basic ROM reflash utility. Proof of life (notice different versions before and after):
<img width="711" alt="Screenshot 2021-07-07 at 00 04 10" src="https://user-images.githubusercontent.com/2096421/124677523-916b2900-deb8-11eb-8237-c8b39f07b080.png">

2021-07-07 00:22 UTC, 0xTJ requested changes

2021-07-07 07:48 UTC, roscopeco commented on code/software/libs/src/sst_flash/sst.c
> +}
Good call, will do 👍

2021-07-07 07:53 UTC, roscopeco commented on code/software/libs/src/sst_flash/sst.c
> +}
Done :)

2021-07-07 10:57 UTC, 0xTJ approved these changes
I'm happy with the way things look here, and I'm able to build and run till expected failure on my end. :)

2021-07-07 21:42 UTC, merged