Fix pack numbers in BOMs
rosco-m68k/rosco_m68k pull request #404
Opened 2024-01-07 11:52 UTC by roscopeco

2024-01-07 13:55 UTC, 0xTJ requested changes
Looks good, just one issue and a small note. :smiley:

2024-01-07 13:55 UTC, 0xTJ commented on docs/r2_030_r2.00_bom.pdf
There are some empty lines after the LED4,LED2 row, which don't seem to be used.

2024-01-07 13:55 UTC, 0xTJ commented on docs/r2_030_r2.00_bom.pdf
The package field for the MC68030RC has MC68020RC.

2024-01-13 23:39 UTC, roscopeco commented on docs/r2_030_r2.00_bom.pdf
Good spot, don't know how I missed that :D 

Thanks, fixed.

2024-01-13 23:39 UTC, roscopeco commented on docs/r2_030_r2.00_bom.pdf
Also good spot, thanks again, fixed :)

2024-01-14 00:06 UTC, 0xTJ approved these changes
As far as I can tell, it looks good! :+1:

2024-01-14 00:28 UTC, merged